name = "QuantumMereology"
uuid = "22b76182-c6fc-4dfd-b616-533ca7f85f8c"
authors = ["Nicolas Loizeau"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
